# Build the React app for production
FROM node:18-alpine AS build

ENV VITE_SERVER_URL=https://server-bdwsmnrktq-lz.a.run.app
ENV VITE_ENVIRONMENT=production
ENV VIRE_CLIENT_URL=https://drikkekompis.eu

WORKDIR /app/client
COPY ./package*.json ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "serve"]
