# Build the React app for production
FROM node:18-alpine

ENV VITE_SERVER_URL=https://server-wyqxm5q4yq-lz.a.run.app/
ENV VITE_ENVIRONMENT=production
ENV VITE_CLIENT_URL=https://drikkekompis.eu

WORKDIR /app/client
COPY ./package*.json ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "serve"]
