export const categorySynonyms: Record<string, string[]> = {
  øl: ["øll", "øllet", "ølet", "juleøl", "juleølet"],
  brennevin: ["sprit"],
  rødvin: ["rød vin"],
  hvitvin: ["hvit vin"],
  musserende_vin: [
    "musserende",
    "sparkling",
    "sprudlevann",
    "bobler",
    "sprudlende",
    "sprudlende vin",
    "sprudlevin",
  ],

  sterkvin: ["dessertvin"],
  rosévin: ["rosevin "],
  perlende_vin: ["Perlende vin"],
  mjød: ["Mjød"],
  alkoholfritt: ["Alkoholfritt"],
  sider: [
    "sider",
    "cider",
    "eplecider",
    "eplesider",
    "pæresider",
    "pære cider",
    "eple cider",
    "eple sider",
    "pære sider",
    "pære cider",
  ],
  sake: ["Sake"],
  fruktvin: ["Fruktvin"],
  // Legg til flere kategorier med synonymer her, hvis nødvendig
};

export const subCategorySynonyms: Record<string, string[]> = {
  øl_india_pale_ale: ["India pale ale", "IPA", "indian pale ale"],
  brennevin_likør: ["likør"],
  brennevin_druebrennevin: ["Druebrennevin"],
  øl_lys_ale: ["lys ale"],
  brennevin_whisky: ["Whisky"],
  øl_porter___stout: ["Porter & stout", "porter", "stout"],
  øl_mørk_lager: ["Mørk lager", "lager"],
  musserende_vin_musserende_vin: ["Musserende vin"],
  sterkvin_vermut: ["Vermut"],
  brennevin_brennevin_annet: ["Brennevin, annet"],
  sterkvin_sterkvin_annen: ["Sterkvin, annen"],
  øl_saison_farmhouse_ale: ["Saison farmhouse ale"],
  sterkvin_portvin: ["Portvin"],
  brennevin_vodka: ["Vodka"],
  øl_surøl: ["Surøl"],
  øl_barley_wine: ["Barley wine"],
  perlende_vin_perlende_vin_hvit: ["Perlende vin, hvit"],
  brennevin_bitter: ["Bitter"],
  øl_klosterstil: ["Klosterstil"],
  alkoholfritt_alkoholfri_rødvin: ["Alkoholfri rødvin"],
  brennevin_gin: ["Gin"],
  alkoholfritt_alkoholfri_musserende_øvrig: [
    "Alkoholfri musserende",
    "alkoholfritt musserende",
  ],
  alkoholfritt_alkoholfritt_øl: ["Alkoholfritt øl"],
  brennevin_rom: ["Rom"],
  alkoholfritt_tonic_og_soda: ["Tonic og soda"],
  musserende_vin_musserende_vin_rosé: ["Musserende vin, rosé"],
  brennevin_fruktbrennevin: ["Fruktbrennevin"],
  brennevin_akevitt: ["Akevitt"],
  øl_lys_lager: ["Lys lager"],
  alkoholfritt_alkoholfri_sider: ["Alkoholfri sider"],
  øl_brown_ale: ["Brown ale"],
  alkoholfritt_alkoholfri_most: ["Alkoholfri most"],
  alkoholfritt_alkoholfri_musserende_vin: ["Alkoholfri musserende vin"],
  perlende_vin_perlende_vin_rosé: ["Perlende vin, rosé"],
  alkoholfritt_alkoholfri_ingefærøl: ["Alkoholfri ingefærøl"],
  sterkvin_sherry: ["Sherry"],
  alkoholfritt_alkoholfritt_øvrig: ["Alkoholfritt, øvrig"],
  øl_pale_ale: ["Pale ale"],
  øl_hveteøl: ["Hveteøl"],
  sterkvin_madeira: ["Madeira"],
  øl_spesial: ["Spesial"],
  musserende_vin_champagne_extra_brut: [
    "Champagne extra brut",
    "champagne",
    "sjampis",
    "sjampanje",
  ],
  musserende_vin_champagne_brut: [
    "Champagne, brut",
    "champagne",
    "sjampis",
    "sjampanje",
  ],
  øl_red_amber: ["Red/amber", "red ale", "amber"],
  alkoholfritt_alkoholfri_rosévin: ["Alkoholfri rosévin"],
  alkoholfritt_alkoholfri_hvitvin: ["Alkoholfri hvitvin"],
  alkoholfritt_alkoholfri_cocktail: ["Alkoholfri cocktail"],
  brennevin_genever: ["Genever"],
  alkoholfritt_limonade: ["Limonade"],
  musserende_vin_champagne_rosé: [
    "Champagne, rosé",
    "champagne",
    "sjampis",
    "sjampanje",
  ],
  perlende_vin_perlende_vin_rød: ["Perlende vin"],
  // Legg til flere kategorier med synonymer her, hvis nødvendig
};
